# Site settings

title: Strata 
email: justin.ellis18@gmail.com 

description: > 
  Personal website of Justin Ellis.
baseurl: "" 
url: "http://localhost:4000" 


twitter_username:     justinellis18 
github_username:      jellis18  
linkedin_username:    justin-ellis-44a32788
google_plus_username:   
facebook_username:    justin.ellis.7967  
dribbble_username:      

# Build settings
sass:
  sass_dir: _sass
  include: ['_pages']
  kramdown:
    input: GFM
