# Site settings

title: Justin A. Ellis
email: justin.ellis18@gmail.com 

description: > 
  Personal website of Justin Ellis.
baseurl: "" 
url: "http://localhost:4000" 

twitter_username:     justinellis18 
github_username:      jellis18  
linkedin_username:    justin-ellis-44a32788
google_plus_username:   
facebook_username:    justin.ellis.7967  
dribbble_username:      

# Build settings
sass:
    sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
    input: GFM
    hard_wrap: false
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    smart_quotes: lsquo,rsquo,ldquo,rdquo
    enable_coderay: false

# pages
pages_list:
    About: '#one'
    CV/Resume: '#two'
    Research: '#three'
    Publications: '#four'
    Contact: '#five'
    Blog: '/blog'
